name: Deploy
on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # 如果你以后改用 submodule 方式
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true # 必须开启 extended 版本以支持 Stack 主题的 SCSS

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: actions/deploy-pages@v4